---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: hermetic-build-run-
spec:
  pipelineRef:
    name: hermetic-build
  params:
    - name: URL
      value: "https://github.com/brunoapimentel/pip-cryptography-sample"
    - name: REF
      value: "main"
    - name: IMAGE
      value: "quay.io/bpimente/test-images:multi-arch-test"
    - name: PREFETCH_INPUT
      value: "pip"
    - name: TARGET_ARTIFACT
      value: "quay.io/bpimente/test-images"
  taskRunTemplate:
    serviceAccountName: registry-credentials
