---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: hermetic-build-run-
spec:
  pipelineRef:
    name: hermetic-build
  params:
    - name: URL
      value: "https://github.com/brunoapimentel/pip-cryptography-sample.git"
    - name: REF
      value: "main"
    - name: IMAGE
      value: "quay.io/bpimente/test-images:multi-arch-test"
    - name: PREFETCH_INPUT
      value: "pip"
    - name: TARGET_ARTIFACT
      value: "quay.io/bpimente/test-images"
    - name: PLATFORMS
      value:
        - linux/x86_64
        - linux/arm64
        - linux/s390x
    - name: PREFETCH_INPUTS
      value:
        - '{"platform": "linux/x86_64", "input": {"type": "pip", "binary": {"os": "manylinux", "py_version": "311", "arch": "x86_64"}}}'
        - '{"platform": "linux/arm64", "input": {"type": "pip", "binary": {"os": "manylinux", "py_version": "311", "arch": "aarch64"}}}'
        - '{"platform": "linux/s390x", "input": {"type": "pip", "binary": {"os": "manylinux", "py_version": "311", "arch": "s390x"}}}'
  taskRunTemplate:
    serviceAccountName: registry-credentials
