---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build
spec:
  description: Build container image using source code and prefetched dependencies
  params:
    - name: PLATFORM
      description: The target platform on which the build will be performed
      type: string
    - name: ARTIFACTS
      description: JSON object containing source_artifact and prefetch_artifact URIs from prefetch task
      type: array
    - name: IMAGE
      description: Reference of the image buildah will produce
      type: string
    - name: DOCKERFILE
      description: Path to the Dockerfile to build
      type: string
      default: "Dockerfile"
  results:
  volumes:
    - name: workdir
      emptyDir: {}
  steps:
    - name: parse-artifacts
      image: quay.io/konflux-ci/buildah-task:latest@sha256:27400eaf836985bcc35182d62d727629f061538f61603c05b85d5d99bfa7da2d
      args:
        - $(params.ARTIFACTS[*])
      env:
        - name: PARAM_PLATFORM
          value: $(params.PLATFORM)
      script: |
        #!/bin/sh
        set -ex

        # This taskRun will receive a list of JSON objects and needs to find, based on the platform param, which one is appliable.
        # The keys will then be split and shared among the other steps via files on the volumeMount.
        for artifact in "$@"; do
          arch=$(echo "$artifact" | jq -r ".platform")
          if [ "$arch" = "$PARAM_PLATFORM" ]; then
            SELECTED_ARTIFACT="$artifact"
          fi
        done

        if [ -z "$SELECTED_ARTIFACT" ]; then
          echo "ERROR: No prefetch artifacts found for platform: $PARAM_PLATFORM" >&2
          exit 1
        fi

        echo $SELECTED_ARTIFACT | jq -r ".source_artifact" > /var/workdir/source-artifact-uri
        echo $SELECTED_ARTIFACT | jq -r ".prefetch_artifact" > /var/workdir/prefetch-artifact-uri
        echo $SELECTED_ARTIFACT | jq -r ".platform" > /var/workdir/platform-string
      volumeMounts:
        - mountPath: /var/workdir
          name: workdir
    - name: use-trusted-artifact
      image: quay.io/konflux-ci/build-trusted-artifacts:latest@sha256:43d997ac61bef77eaee0413fe50c29b66eb4d0d32066f5bd4a83f39e4b2d9457
      script: |
        #!/bin/sh
        set -ex

        SOURCE_ARTIFACT=$(cat /var/workdir/source-artifact-uri)
        PREFETCH_ARTIFACT=$(cat /var/workdir/prefetch-artifact-uri)
        /usr/local/bin/entrypoint use \
          "$SOURCE_ARTIFACT=/var/workdir/source" \
          "$PREFETCH_ARTIFACT=/var/workdir/prefetch"
      volumeMounts:
        - mountPath: /var/workdir
          name: workdir
    - name: build
      image: quay.io/konflux-ci/buildah-task:latest@sha256:27400eaf836985bcc35182d62d727629f061538f61603c05b85d5d99bfa7da2d
      volumeMounts:
        - mountPath: /var/workdir
          name: workdir
      workingDir: /var/workdir/source
      env:
        - name: PARAM_IMAGE
          value: $(params.IMAGE)
        - name: PARAM_DOCKERFILE
          value: $(params.DOCKERFILE)
        - name: PREFETCH_PATH
          value: /var/workdir/prefetch
        - name: SOURCE_PATH
          value: /var/workdir/source
        - name: PARAM_PLATFORM
          value: $(params.PLATFORM)
      securityContext:
        capabilities:
          add:
          - SETFCAP
      script: |
        #!/bin/sh
        set -ex

        echo "Building for $PARAM_PLATFORM"
        echo "Using artifact $(cat /var/workdir/prefetch-artifact-uri)"
        echo "Prefetched content: "
        find "$PREFETCH_PATH"
        if [ "$PARAM_PLATFORM" != "linux/x86_64" ]; then
          echo "Skipping build since this architecture is not available"
          exit 0
        fi

        # Append the platform to the image URL
        PLATFORM=$(cat /var/workdir/platform-string | sed "s/linux\///")
        IMAGE_WITH_ARCH="$PARAM_IMAGE-$PLATFORM"
        echo $IMAGE_WITH_ARCH > /var/workdir/image-with-arch-string

        # Copy the dockerfile and inject the command that sources the prefetch env
        dockerfile_path=$PARAM_DOCKERFILE
        dockerfile_copy=$(mktemp --tmpdir "$(basename "$dockerfile_path").XXXXXX")
        cp "$dockerfile_path" "$dockerfile_copy"

        sed -E -i \
          -e 'H;1h;$!d;x' \
          -e 's@^\s*(run((\s|\\\n)+-\S+)*(\s|\\\n)+)@\1. /prefetch/prefetch.env \&\& \\\n    @igM' \
          "$dockerfile_copy"

        # Mount the prefetched content
        VOLUME_MOUNTS=()

        cp -r "$PREFETCH_PATH" /tmp/
        chmod -R go+rwX /tmp/prefetch
        VOLUME_MOUNTS+=(--volume /tmp/prefetch:/prefetch)

        # Build with network isonlation
        buildah_cmd_array=(
          buildah build
          "${VOLUME_MOUNTS[@]}"
          --tls-verify="true"
          --no-cache
          --ulimit nofile=4096:4096
          --http-proxy=false
          --network=none
          -f "$dockerfile_copy" -t "$IMAGE_WITH_ARCH" .
        )

        buildah_cmd=$(printf "%q " "${buildah_cmd_array[@]}")

        $buildah_cmd

        # Push the built image
        buildah push \
        --format=docker \
        --retry 3 \
        --tls-verify=true \
        "$IMAGE_WITH_ARCH"
    
    - name: push-sbom
      image: quay.io/konflux-ci/appstudio-utils:1610c1fc4cfc9c9053dbefc1146904a4df6659ef@sha256:90ac97b811073cb99a23232c15a08082b586c702b85da6200cf54ef505e3c50c
      volumeMounts:
        - mountPath: /var/workdir
          name: workdir
      script: |
        #!/bin/sh
        set -ex

        IMAGE_WITH_ARCH_PATH="/var/workdir/image-with-arch-string"

        if [ -f "$IMAGE_WITH_ARCH_PATH" ]; then
          IMAGE_WITH_ARCH=$(cat "$IMAGE_WITH_ARCH_PATH")
          cosign attach sbom --sbom /var/workdir/prefetch/output/bom.json --type "spdx" "$IMAGE_WITH_ARCH"
        fi
