---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
spec:
  description: Clone a repository and push the cloned files as an artifact
  params:
    - name: URL
      description: Repository URL to clone from
      type: string
    - name: REF
      description: Commit to checkout (branch, tag, sha, etc.)
      type: string
    - name: TARGET_ARTIFACT
      description: The OCI repository where the artifact will be stored
      type: string
  results:
    - name: SOURCE_ARTIFACT
      description: The Trusted Artifact URI pointing to the artifact with the cloned files
      type: string
  volumes:
    - name: workdir
      emptyDir: {}
  steps:
    - name: clone
      image: quay.io/konflux-ci/git-clone@sha256:aedc5ba99f95c3d77fc256ac01677212c18298373a0b3de3aeabc41ba69cc301
      volumeMounts:
        - mountPath: /var/workdir
          name: workdir
      env:
        - name: PARAM_URL
          value: $(params.URL)
        - name: PARAM_REF
          value: $(params.REF)
      script: |
        #!/bin/sh
        set -ex
        git clone "${PARAM_URL}" /var/workdir/source
        cd /var/workdir/source
        git checkout "${PARAM_REF}"
    - name: create-trusted-artifact
      image: quay.io/konflux-ci/build-trusted-artifacts:latest@sha256:43d997ac61bef77eaee0413fe50c29b66eb4d0d32066f5bd4a83f39e4b2d9457
      args:
        - create
        - --store
        - $(params.TARGET_ARTIFACT)
        - $(results.SOURCE_ARTIFACT.path)=/var/workdir/source
      volumeMounts:
        - mountPath: /var/workdir
          name: workdir
