---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: hermetic-build
spec:
  description: Pipeline that clones a repositoty, prefetches its dependencies and builds it hermetically
  params:
    - name: URL
      description: Repository URL to clone from
      type: string
    - name: REF
      description: Commit to checkout (branch, tag, sha, etc.)
      type: string
    - name: IMAGE
      description: Reference of the image buildah will produce
      type: string
    - name: TARGET_ARTIFACT
      description: The OCI repository where the artifacts will be stored
      type: string
    - name: PLATFORMS
      description: The target platforms on which the build will be performed
      type: array
    - name: PREFETCH_INPUTS
      description: Configures project packages that will have their dependencies prefetched
      type: array
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: URL
          value: $(params.URL)
        - name: REF
          value: $(params.REF)
        - name: TARGET_ARTIFACT
          value: $(params.TARGET_ARTIFACT)
    - name: prefetch
      matrix:
        params:
          - name: PLATFORM
            value:
              - $(params.PLATFORMS)
      taskRef:
        name: prefetch-dependencies
      params:
        - name: SOURCE_ARTIFACT
          value: $(tasks.clone.results.SOURCE_ARTIFACT)
        # Because of Tekton limitations, the inputs for all archs need to be passed here.
        # Choosing the right one based on the architecture will be done inside the Task.
        - name: PREFETCH_INPUTS
          value:
            - $(params.PREFETCH_INPUTS[*])
        - name: TARGET_ARTIFACT
          value: $(params.TARGET_ARTIFACT)
      runAfter:
        - clone
    - name: build
      matrix:
        params:
          - name: PLATFORM
            value:
              - $(params.PLATFORMS[*])
      taskRef:
        name: build
      params:
        - name: ARTIFACTS
          value:
            - $(tasks.prefetch.results.ARTIFACTS[*])
        - name: IMAGE
          value: $(params.IMAGE)
      runAfter:
        - prefetch
